name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "e1bf3a83-ed5b-4a60-8289-884fc30ac139"

[[kv_namespaces]]
binding = "kv"
id = "8c1040b6a184439f8dff05458f1c5532"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail"

[vars]
orm_log = false
domain = ["lfxas.qzz.io"]
admin = "admin@lfxas.qzz.io"
jwt_secret = "K8mP3xR7vQ2wL9nF4yT6hB1jD5sN0aZ8"
